### ISSUE TITLE
Method to log the IMU data

### ISSUE THREAD

**Issue by Airrey97** [zinuok/kaistviodataset#1]
Excuse me, I wonder how to get the IMU data from pixhawk with a high frequency(such as 100Hz or more)?  Do you use Mavros to connect the  px4 with onboard computer?

**Comment by zinuok** [comment]
Yes. I used mavros to get data from px4. To get the IMU data at such a fast frequency, you first need to change the settings of pixhawk. You should change the file inside the sd card inserted into the pixhawk. This is solved by including the following in /etc/extras.txt on the sd card:

mavlink stream -d /dev/ttyACM0 -s ATTITUDE -r 100
mavlink stream -d /dev/ttyACM0 -s ATTITUDE_QUATERNION -r 100
mavlink stream -d /dev/ttyACM0 -s HIGHERS_IMU -r 100

for more information, please refer https://github.com/mavlink/mavros/issues/589
Sincerely

**Comment by Airrey97** [comment]
Thank you! I will have a try
